### ISSUE TITLE
RuntimeError: the derivative for 'symeig' is not implemented

### ISSUE THREAD

**Issue by prtsk** [Michaelvll/DeepCCA#1]
It appears as though the symeig function used in cca_loss is not being executed well.
I tried to run your example in run.ipynb and I encounter the run time error mentioned. Would you happen to know how to fix this?

**Comment by Michaelvll** [comment]
Hi, could you please double check the version of your pytorch? Actually, the derivative of `symeig` is not implemented until the pytorch 1.0.

**Comment by prtsk** [comment]
I have the latest version of pytorch and this problem seems to persist.

**Comment by prtsk** [comment]
Seems like the fix is only on CUDA.

**Comment by Michaelvll** [comment]
Yes, this repo is not fully tested on CPU, but the cuda version should work properly.
