### ISSUE TITLE
about the 'linear_cca'

### ISSUE THREAD

**Issue by zjzzzz** [Michaelvll/DeepCCA#2]
Hi, thanks for the code which is exactly I'm looking for. But, I think that the 'linear_cca' should not be applied in the test but in the train (main.py). Then we'd better record the w[0], w[1], m[0], m[1] and apply them in the test.
If I am wrong, please let me know.
Thank you very much!

**Comment by Michaelvll** [comment]
Yes, you are right! I have found this error before, but forgot to push to this repo. I will fix it shortly.

**Comment by Michaelvll** [comment]
I commit a fix https://github.com/Michaelvll/DeepCCA/commit/27d76987376ac4e2ca928fa2885bc8bebf4077de for the training process of linear_cca, but its not elegant enough for saving the linear cca part. I will fix it in future when I get more spare time. If there is any other problems, please let me know.
