### ISSUE TITLE
symeig_cuda: the algorithm failed to converge

### ISSUE THREAD

**Issue by TissueC** [Michaelvll/DeepCCA#6]
When I used deepCCA on my dataset, the error happened:

`RuntimeError: symeig_cuda: the algorithm failed to converge; 9 off-diagonal elements of an intermediate tridiagonal form did not converge to zero.`

Till now I don't know what leads to this problem. Any comments will be highly appreciated.
The shared google colab script: https://colab.research.google.com/drive/1_446LPQIoR4Hy9ztzw0nvSPvraIUZ8gZ

I tried the default dataset MNIST and no such problem happened.

**Comment by arminarj** [comment]
Hi @TissueC, 
have you uncommented the `assert` lines for better understanding the problem?

**Comment by TissueC** [comment]
After I do z-score to the original data( in scikit-learn, i.e. standard scalar), the problem is solved. I guess this problem may involve in some values (not smooth) in my feature matrix.

**Comment by arminarj** [comment]
Yes, you are right. As far as I know, you should normalize the input data before the whole process. Please let us know if you have any further questions.
Good luck

**Comment by Michaelvll** [comment]
The problem seems solved, according to @TissueC. I am now closing this issue. Please feel free to reopen the issue, if there are any further questions.
