### ISSUE TITLE
Linear CCA solution

### ISSUE THREAD

**Issue by vinsis** [Michaelvll/DeepCCA#7]
Hi @Michaelvll thank you for this implementation. I have a question regarding the closed form solution of weight matrix as implemented in [these lines](https://github.com/Michaelvll/DeepCCA/blob/master/linear_cca.py#L49-L50)

```python
self.w[0] = numpy.dot(SigmaHat11RootInv, U[:, 0:outdim_size])
self.w[1] = numpy.dot(SigmaHat22RootInv, V[:, 0:outdim_size])
```

Here U is the matrix of eigenvectors of 
```python
Tval = numpy.dot(numpy.dot(SigmaHat11RootInv, SigmaHat12), SigmaHat22RootInv)
```

According to slide 8 of  [these notes](http://users.stat.umn.edu/~helwig/notes/cancor-Notes.pdf) the solution is given by:

<img width="752" alt="Screen Shot 2020-06-17 at 5 25 17 PM" src="https://user-images.githubusercontent.com/6437295/84881104-fee6c480-b0bf-11ea-82be-6d5565123786.png">

Thus, `U` should be the eigenvector matrix of 

```python
SigmaHat11RootInv * SigmaHat12 * SigmaHat22RootInv * SigmaHat12Root * SigmaHat11RootInv
```

instead of 
```python
SigmaHat11RootInv * SigmaHat12 * SigmaHat22RootInv
```

as implemented in your code. 

I believe your implementation is correct since it gives good results. However I would appreciate it if you could explain the discrepancy between the image above and your implementation. Thank you.

**Comment by arminarj** [comment]
Hi @vinsis ,  Thanks for your interest.

I think you missed a part of the Slides process, lets use a single notion for describing the method.

let `W_1` and `W_2` denote the desired matrix projections.

Duo to the slides definitions the W_1 should be :

``W_1 = u_k.transpose() @ SigmaHat11RootInv``

which `u_k` is : 

`SigmaHat11RootInv * SigmaHat12 * SigmaHat22RootInv * SigmaHat12Root * SigmaHat11RootInv`

as you said. but the CCA projections are the matrix multiplication of the `u_k.transpose()` and the `SigmaHat11RootInv `.

And I think if you write the `W_1` as the full multiplication and then use the `SVD()` to calculate the eigenvectors you will reach the same equation as we implemented in these [Lines](https://github.com/Michaelvll/DeepCCA/blob/2fa648e444fa6ae9135c52cceee1b653cc1d44d0/linear_cca.py#L44-L50)

**Comment by vinsis** [comment]
I see, my bad! Thank you again.
